### ISSUE TITLE
Receiving log flood of Undefined Index errors

### ISSUE THREAD

**Issue by ChrisWiegman** [nextcloud/bookmarks#1143]
**Describe the bug**
My logs are being flooded with the following error:

```Undefined index: sharee at /var/www/html/custom_apps/bookmarks/lib/Activity/Provider.php#64```

**To Reproduce**
1. Go to `Settings -> Logging`
2. See error

**Expected behavior**
While occasional errors would be expected I am receiving hundreds per day on my little 2-person instance. I would expect that I wouldn't receive these.

**Screenshots**

![Screenshot from 2020-08-04 08-31-53](https://user-images.githubusercontent.com/394675/89294086-fb39dd80-d62c-11ea-94ce-bac0449ec3a1.png)

**Desktop (please complete the following information):**
 - OS: Pop_OS 20.04
 - Browser Firefox
 - Version 2.6.5

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nextcloud Docker "latest"
 - Database MariaDB 10
 - Bookmarks app version: Latest
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
N/A
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
See above

**Browser log**
```
N/A
```

**Comment by marcelklehr** [comment]
Thanks for reporting this. I've fixed this and will release the fix with the next version.

**Comment by radoeka** [comment]
> Is it possible to reopen this bugreport, please.  I applied the patch, but I'm still getting the errors.

I restarted apache2 and logged out and in again, and that have helped.  So far so good.

**Comment by radoeka** [comment]
> I restarted apache2 and logged out and in again, and that have helped. So far so good.

I thought that helped, but does not :( 
I'm still getting the error.


I'm referring to this patch: https://github.com/nextcloud/bookmarks/commit/9962a681402b5831f1ef5d9dc8c6c0f67b444ab0#diff-f3633662824a9682b62b1f1a4fdd63c1

I created this patch out of it:
```
diff -Naur Activity/Provider.php Activity-new/Provider.php
--- Activity/Provider.php       2020-07-23 16:46:36.000000000 +0200
+++ Activity-new/Provider.php   2020-08-11 21:14:18.435825325 +0200
@@ -61,7 +61,7 @@
                $subjectParameters = $event->getSubjectParameters();
 
                $isSharee = $event->getAffectedUser() === $this->activityManager->getCurrentUserId();
-               $sharee = $this->userManager->get($subjectParameters['sharee']);
+               $sharee = $subjectParameters['sharee'] ? $this->userManager->get($subjectParameters['sharee']) : null;
                if ($sharee !== null) {
                        $shareeName = $sharee->getDisplayName();
                }else{
```

Deatils:

![image](https://user-images.githubusercontent.com/2937666/89942931-af36fc00-dc1d-11ea-8c62-a9a4cd230569.png)

The error is reported at least 2 times, when bookmarks is accessed.
When 'Not tagged' apps/bookmarks/untagged, it is 4 times reported.

Default sort order in my case: most recent (changing that, did not make a difference).

Did I miss something, or is more needed to fix this?

**Comment by marcelklehr** [comment]
Ah, that was a mind-o. It should have been

```
$sharee = isset($subjectParameters['sharee']) ? $this->userManager->get($subjectParameters['sharee']) : null;
```

**Comment by radoeka** [comment]
@marcelklehr : that's it indeed :)
