### ISSUE TITLE
CSRF check failing for saving bookmarks with 3.3.3 and Nextcloud 19.01

### ISSUE THREAD

**Issue by rtyler** [nextcloud/bookmarks#1148]
**Describe the bug**

Upgraded to 3.3.3 and I'm seeing this issue, cannot tell if it's new or not. But basically the JSON response from the 

```json
{"message":"CSRF check failed"}
```
The failure comes from  https://DOMAIN/nextcloud/index.php/apps/bookmarks/bookmark
 
There is a `requesttoken` associated with the request, I'm assuming that's the CSRF token needed.

**To Reproduce**
1. Go to the bookmarks app
2. Click on new bookmark
3. Add URL
4. "Failed to save bookmark" (details gleaned from the browser developer console)

**Expected behavior**

Bookmark saving :smiling_imp: 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 78.0.2

**Server (please complete the following information):**
 - OS: Linux
 - HTTP server: Apache 2
 - Database MySQL
 - Nextcloud version: 19.0.1
 - Bookmarks app version: 3.3.3

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Mmh, does this happen consistently?

Perhaps the service worker is the problem. can you try disabling it as folllows:

1. Press F12
2. Go to the "application" tab and disable the service worker

**Comment by marcelklehr** [comment]
This should be fixed with v3.3.4, can you confirm?

**Comment by rtyler** [comment]
When disabling the service worker, the same CSRF error is still persisted. I have also upgraded to 3.3.4 and it's still no good. 

Would that CSRF check make any useful logs on the server side that might help us isolate this?

**Comment by rtyler** [comment]
I just noticed something interesting! The bookmarklet was able to save a bookmark, but the "New bookmark" within the app could not. Most curious!

**Comment by rtyler** [comment]
With 3.4.3 this error appears to have gone away, so I'm going to close this :shrug:
